// Test generated by RoostGPT for test petclinic-springboot using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ui.Model;

public class OwnerController_initCreationForm_7ad03dd574_Test {

    private OwnerController ownerController;
    private Map<String, Object> model;

    @BeforeEach
    public void setUp() {
        ownerController = new OwnerController();
        model = new HashMap<>();
    }

    @Test
    public void testInitCreationForm_Success() {
        String viewName = ownerController.initCreationForm(model);
        assertEquals("owners/createOrUpdateOwnerForm", viewName);
        assertEquals(1, model.size());
        assertEquals(Owner.class, model.get("owner").getClass());
    }

    @Test
    public void testInitCreationForm_WithExistingModel() {
        model.put("owner", new Owner());
        String viewName = ownerController.initCreationForm(model);
        assertEquals("owners/createOrUpdateOwnerForm", viewName);
        assertEquals(1, model.size());
        assertEquals(Owner.class, model.get("owner").getClass());
    }
}
