// Test generated by RoostGPT for test petclinic-springboot using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class PetController_PetController_2c07014f29_Test {

    @Autowired
    private PetController petController;

    @MockBean
    private OwnerRepository ownerRepository;

    @BeforeEach
    public void setup() {
        assertNotNull(petController);
    }

    @Test
    public void testPetControllerConstructor() {
        OwnerRepository mockOwnerRepository = Mockito.mock(OwnerRepository.class);
        PetController petController = new PetController(mockOwnerRepository);
        assertNotNull(petController);
    }

    @Test
    public void testPetControllerConstructor_NullOwnerRepository() {
        try {
            new PetController(null);
        } catch (IllegalArgumentException e) {
            assertEquals("OwnerRepository must not be null", e.getMessage());
        }
    }
}
